version: '3'

services:
  db:
    image: mysql:5.7
    container_name: mysql_test
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: db_user
      MYSQL_PASSWORD: root
      TZ: 'Asia/Tokyo'
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - '3306:3306'
